
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk

###

GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk
###

POST http://localhost:3000/districts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

GET http://localhost:3000/districts/50/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk

###

DELETE http://localhost:3000/districts/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk
###

PUT http://localhost:3000/districts/15/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/3/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYwNjMxNzExfQ.xsBRpb1R5EDFqRC6gSeTVlb7Px2hRMeRWf_HBgkM9Jk
###

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}